@extends('layouts.app')

@section('title', $lead->lead_code.' | Sales Monitoring')

@section('content')
<main class="min-h-[calc(100svh-74px)] bg-slate-50 px-4 py-5 sm:px-7 lg:px-10">
    <section class="mx-auto max-w-7xl">
        <div class="flex flex-col gap-4 rounded-3xl bg-gradient-to-r from-slate-950 via-blue-950 to-cyan-700 p-6 text-white shadow-xl lg:flex-row lg:items-center lg:justify-between">
            <div><a class="mb-3 inline-flex items-center gap-2 text-sm font-bold text-cyan-100 no-underline hover:text-white" href="{{ route('yatira.sales.index') }}"><i class="bi bi-arrow-left"></i> Sales Monitoring</a><p class="mb-1 text-xs font-extrabold uppercase tracking-[.18em] text-cyan-200">Sales Lead</p><h1 class="m-0 text-2xl font-black sm:text-3xl">{{ $lead->lead_code }}</h1><p class="mb-0 mt-1 text-blue-100">{{ $lead->client_name }} · {{ $lead->project_name }}</p></div>
            <div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-white/10 px-4 py-2 text-sm font-extrabold">{{ $lead->stage->name }}</span><span class="rounded-full bg-cyan-300 px-4 py-2 text-sm font-black text-blue-950">{{ number_format((float)$lead->probability_percent,0) }}%</span></div>
        </div>

        @if(session('success'))<div class="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 font-semibold text-emerald-800"><i class="bi bi-check-circle-fill me-2"></i>{{ session('success') }}</div>@endif
        @if($errors->any())<div class="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-800"><p class="mb-1 font-extrabold">The action could not be completed:</p><ul class="mb-0 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <div class="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
            <div class="space-y-5">
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
                    <header class="flex flex-col gap-3 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="m-0 text-lg font-black text-slate-900">Lead Information</h2><p class="mb-0 mt-1 text-sm text-slate-500">Client, project and commercial details.</p></div>@if($canUpdate && $lead->status!=='CANCELLED')<div class="flex flex-wrap gap-2"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editLeadModal"><i class="bi bi-pencil me-1"></i>Edit</button>@if($lead->status!=='AWARDED')<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#stageModal"><i class="bi bi-arrow-up-right-circle me-1"></i>Update Stage</button>@endif</div>@endif</header>
                    @php($details=[['Date Registered',$lead->date_registered?->format('M d, Y')],['Client',$lead->client_name],['Contact Person',$lead->contact_person],['Contact Number',$lead->contact_number],['Email',$lead->email],['Client Address',$lead->client_address],['Project',$lead->project_name],['Project Type',$lead->project_type],['Location',$lead->project_location],['Estimated Value','₱'.number_format((float)$lead->estimated_value,2)],['Lead Source',$lead->lead_source],['Expected Close',$lead->expected_close_date?->format('M d, Y')],['Assigned Agent',$lead->agent?trim($lead->agent->name.' '.$lead->agent->lastname):'Unassigned'],['Registered By',trim(($lead->creator?->name??'').' '.($lead->creator?->lastname??''))]])
                    <dl class="grid grid-cols-1 gap-x-6 gap-y-5 p-5 sm:grid-cols-2 lg:grid-cols-3">@foreach($details as [$label,$value])<div class="min-w-0"><dt class="text-xs font-extrabold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mb-0 mt-1 break-words font-bold text-slate-800">{{ filled($value)?$value:'—' }}</dd></div>@endforeach</dl>
                    @if($lead->project_description || $lead->remarks)<div class="grid gap-4 border-t border-slate-100 p-5 md:grid-cols-2">@if($lead->project_description)<div><h3 class="text-sm font-extrabold text-slate-900">Project Description</h3><p class="mb-0 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $lead->project_description }}</p></div>@endif @if($lead->remarks)<div><h3 class="text-sm font-extrabold text-slate-900">Remarks</h3><p class="mb-0 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $lead->remarks }}</p></div>@endif</div>@endif
                </section>

                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 p-5"><h2 class="m-0 text-lg font-black text-slate-900">Sales Progress</h2><p class="mb-0 mt-1 text-sm text-slate-500">Probability is calculated automatically from the current stage.</p></header><div class="p-5"><div class="mb-2 flex justify-between text-sm font-extrabold"><span>{{ $lead->stage->name }}</span><span>{{ number_format((float)$lead->probability_percent,0) }}%</span></div><div class="h-4 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-gradient-to-r from-cyan-500 to-blue-700" style="width:{{ min(100,(float)$lead->probability_percent) }}%"></div></div><div class="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div class="rounded-xl bg-slate-50 p-3"><span class="block text-slate-500">Status</span><strong class="mt-1 block {{ $lead->status==='CANCELLED'?'text-rose-700':($lead->status==='AWARDED'?'text-emerald-700':'text-blue-800') }}">{{ $lead->status }}</strong></div><div class="rounded-xl bg-slate-50 p-3"><span class="block text-slate-500">Stage Weight</span><strong class="mt-1 block">{{ number_format((float)$lead->stage->weight_percent,0) }}%</strong></div><div class="rounded-xl bg-slate-50 p-3"><span class="block text-slate-500">Weighted Value</span><strong class="mt-1 block">₱{{ number_format((float)$lead->estimated_value*(float)$lead->probability_percent/100,2) }}</strong></div></div></div></section>
            </div>

            <aside class="space-y-5">
                @if($lead->status==='CANCELLED')<section class="rounded-3xl border border-rose-200 bg-rose-50 p-5"><p class="mb-1 text-xs font-extrabold uppercase tracking-wide text-rose-600">Cancelled Lead</p><p class="mb-0 whitespace-pre-line text-sm font-semibold text-rose-900">{{ $lead->cancellation_reason }}</p><small class="mt-2 block text-rose-700">{{ $lead->cancelled_at?->format('M d, Y h:i A') }}</small></section>@elseif($canUpdate && $lead->status!=='AWARDED')<section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-base font-black text-slate-900">Lead Controls</h2><p class="text-sm text-slate-500">Cancellation is permanent in the history and sets probability to 0%.</p><button class="btn btn-outline-danger w-full" data-bs-toggle="modal" data-bs-target="#cancelModal"><i class="bi bi-x-circle me-1"></i>Cancel Lead</button></section>@endif
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 p-5"><h2 class="m-0 text-lg font-black text-slate-900">Permanent History</h2><p class="mb-0 mt-1 text-sm text-slate-500">Every important change remains traceable.</p></header><div class="divide-y divide-slate-100">@forelse($histories as $history)<article class="relative p-5 pl-10"><span class="absolute left-5 top-6 h-3 w-3 rounded-full border-2 border-white bg-blue-700 ring-2 ring-blue-100"></span><strong class="block text-sm text-slate-900">{{ str($history->action)->replace('_',' ')->title() }}</strong>@if($history->fromStage || $history->toStage)<p class="mb-0 mt-1 text-xs font-bold text-blue-700">{{ $history->fromStage?->name ?? 'Start' }} → {{ $history->toStage?->name ?? $lead->status }}</p>@endif @if($history->remarks)<p class="mb-0 mt-2 whitespace-pre-line text-sm text-slate-600">{{ $history->remarks }}</p>@endif<small class="mt-2 block text-slate-400">{{ $history->user ? trim($history->user->name.' '.$history->user->lastname) : 'System' }} · {{ $history->created_at?->format('M d, Y h:i A') }}</small></article>@empty<p class="p-6 text-center text-sm text-slate-500">No history entries.</p>@endforelse</div>@if($histories->hasPages())<div class="border-t border-slate-200 p-4">{{ $histories->links() }}</div>@endif</section>
            </aside>
        </div>
    </section>
</main>

@if($canUpdate && $lead->status!=='CANCELLED')
<div class="modal" id="editLeadModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title">Edit Lead Information</h2><p class="mb-0 text-sm text-slate-500">Changes are saved directly and recorded in history.</p></div><button class="btn-close ml-auto" data-bs-dismiss="modal" aria-label="Close"></button></div><form method="POST" action="{{ route('yatira.sales.update',$lead) }}">@csrf @method('PUT')<div class="modal-body">@include('yatira.sales._fields',['prefix'=>'edit_'])</div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save Changes</button></div></form></div></div></div>
@if($lead->status!=='AWARDED')<div class="modal" id="stageModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title">Update Sales Stage</h2><p class="mb-0 text-sm text-slate-500">Selecting a stage automatically sets its probability.</p></div><button class="btn-close ml-auto" data-bs-dismiss="modal" aria-label="Close"></button></div><form method="POST" action="{{ route('yatira.sales.stage',$lead) }}">@csrf<div class="modal-body"><label for="sales_stage_id">Sales Stage <span class="text-rose-600">*</span></label><select class="form-select" id="sales_stage_id" name="sales_stage_id" required>@foreach($stages as $stage)<option value="{{ $stage->id }}" @selected($lead->sales_stage_id===$stage->id)>{{ $stage->sequence }}. {{ $stage->name }} — {{ number_format((float)$stage->probability_percent,0) }}%</option>@endforeach</select><label class="mt-4" for="stage_remarks">Update Notes</label><textarea class="form-control" id="stage_remarks" name="stage_remarks" rows="4" maxlength="2000" placeholder="Briefly describe the progress or outcome"></textarea></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Update Stage</button></div></form></div></div></div>@endif
@endif
@if($canUpdate && !in_array($lead->status,['CANCELLED','AWARDED'],true))
<div class="modal" id="cancelModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title text-rose-700">Cancel Sales Lead</h2><p class="mb-0 text-sm text-slate-500">The lead stays in permanent history with a 0% probability.</p></div><button class="btn-close ml-auto" data-bs-dismiss="modal" aria-label="Close"></button></div><form method="POST" action="{{ route('yatira.sales.cancel',$lead) }}">@csrf<div class="modal-body"><label for="cancellation_reason">Cancellation Reason <span class="text-rose-600">*</span></label><textarea class="form-control" id="cancellation_reason" name="cancellation_reason" rows="5" maxlength="2000" required></textarea></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Keep Lead</button><button class="btn btn-danger" type="submit">Confirm Cancellation</button></div></form></div></div></div>
@endif
@endsection
