@extends('layouts.app')
@section('title','Organization Setup | Villa Group')
@section('content')
<section class="min-h-[calc(100svh-74px)] bg-slate-50 px-4 py-7 sm:px-8"><div class="mx-auto max-w-7xl">
<header class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-extrabold uppercase tracking-[.16em] text-villa-600">User Management</p><h1 class="m-0 text-3xl font-black text-slate-900">Organization Setup</h1><p class="mt-1 text-sm text-slate-500">Maintain company departments and job positions independently from system access.</p></div><a href="{{ route('users.index') }}" class="inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 no-underline"><i class="bi bi-arrow-left"></i>Back to Users</a></header>
@if(session('success'))<div class="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800">{{ $errors->first() }}</div>@endif
<div class="mb-7 grid gap-5 lg:grid-cols-2"><form method="POST" action="{{ route('users.organization.departments.store') }}" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">@csrf<h2 class="mb-1 text-lg font-black text-slate-900">Add Department</h2><p class="mb-5 text-sm text-slate-500">Departments always belong to one company.</p><div class="grid gap-4 sm:grid-cols-2"><select name="division_id" class="h-12 rounded-xl border border-slate-300 bg-white px-4" required><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select><input name="name" maxlength="255" class="h-12 rounded-xl border border-slate-300 px-4" placeholder="Department name" required></div><button class="mt-4 rounded-xl bg-villa-700 px-5 py-3 text-sm font-extrabold text-white">Add Department</button></form>
<form method="POST" action="{{ route('users.organization.positions.store') }}" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">@csrf<h2 class="mb-1 text-lg font-black text-slate-900">Add Position</h2><p class="mb-5 text-sm text-slate-500">A position is a job title; access is assigned separately on the user account.</p><div class="grid gap-4 sm:grid-cols-2"><select id="orgCompany" name="division_id" class="h-12 rounded-xl border border-slate-300 bg-white px-4" required><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select><select id="orgDepartment" name="department_id" class="h-12 rounded-xl border border-slate-300 bg-white px-4" required><option value="">Select department</option>@foreach($companies->flatMap->departments as $department)<option value="{{ $department->id }}" data-company="{{ $department->division_id }}">{{ $department->name }}</option>@endforeach</select><input name="name" maxlength="255" class="h-12 rounded-xl border border-slate-300 px-4" placeholder="Position title" required><select name="operational_category" class="h-12 rounded-xl border border-slate-300 bg-white px-4" required>@foreach(\App\Http\Controllers\OrganizationController::OPERATIONAL_CATEGORIES as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><textarea name="description" maxlength="1000" rows="2" class="sm:col-span-2 rounded-xl border border-slate-300 px-4 py-3" placeholder="Optional position description"></textarea></div><button class="mt-4 rounded-xl bg-villa-700 px-5 py-3 text-sm font-extrabold text-white">Add Position</button></form></div>
<div class="grid gap-5 xl:grid-cols-2">@foreach($companies as $company)<article class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 bg-gradient-to-r from-villa-800 to-villa-600 px-6 py-5 text-white"><h2 class="mb-0 text-xl font-black">{{ $company->name }}</h2><p class="mb-0 mt-1 text-xs text-white/70">{{ $company->departments->count() }} departments · {{ $company->departments->sum(fn($d)=>$d->positions->count()) }} positions</p></div><div class="divide-y divide-slate-100">@forelse($company->departments as $department)<div class="p-5"><h3 class="mb-3 text-sm font-black text-slate-900">{{ $department->name }}</h3><div class="flex flex-wrap gap-2">@forelse($department->positions as $position)<span class="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700">{{ $position->name }}</span>@empty<span class="text-xs text-slate-400">No positions yet</span>@endforelse</div></div>@empty<div class="p-6 text-sm text-slate-500">No departments configured.</div>@endforelse</div></article>@endforeach</div>
</div></section>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const company=document.getElementById('orgCompany'),department=document.getElementById('orgDepartment');if(!company||!department)return;const options=[...department.options];const filter=()=>{options.forEach(option=>option.hidden=Boolean(option.value&&option.dataset.company!==company.value));if(department.selectedOptions[0]?.hidden)department.value='';};company.addEventListener('change',filter);filter();});</script>@endpush
