@extends('layouts.app')
@section('title','Stock Requests | JMV')
@section('content')
<section class="min-h-[calc(100svh-74px)] bg-slate-50 px-4 py-6 sm:px-7 lg:px-10"><div class="mx-auto max-w-7xl">
@if(session('success'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<header class="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-extrabold uppercase tracking-[.16em] text-amber-700">Controlled Issuance</p><h1 class="m-0 text-2xl font-black text-slate-900 sm:text-3xl">Stock Requests</h1><p class="mt-1 text-sm text-slate-500">Request, authorize and release materials with full accountability.</p></div>@if($canCreate)<button data-bs-toggle="modal" data-bs-target="#requestModal" class="min-h-11 rounded-xl border-0 bg-villa-800 px-4 text-sm font-bold text-white"><i class="bi bi-plus-lg me-2"></i>New Request</button>@endif</header>
<div class="grid gap-4">@forelse($requests as $request)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><strong class="text-lg text-slate-900">{{ $request->request_no }}</strong><span class="rounded-full px-3 py-1 text-xs font-extrabold {{ match($request->status){'PENDING'=>'bg-amber-50 text-amber-700','APPROVED'=>'bg-blue-50 text-blue-700','RELEASED'=>'bg-emerald-50 text-emerald-700',default=>'bg-rose-50 text-rose-700'} }}">{{ $request->status }}</span></div><p class="mb-1 mt-2 text-sm text-slate-700">{{ $request->items->first()?->item?->item_name }} · {{ $request->items->first()?->quantity }} {{ $request->items->first()?->item?->unit }} · {{ $request->items->first()?->location?->name }}</p><p class="m-0 text-xs text-slate-500">Requested by {{ trim(($request->requester?->name??'').' '.($request->requester?->lastname??'')) }} · {{ $request->created_at->format('M d, Y h:i A') }}</p><p class="mb-0 mt-2 text-sm text-slate-600">{{ $request->purpose }}</p>@if($request->approval_remarks)<p class="mb-0 mt-2 rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-600">Review: {{ $request->approval_remarks }}</p>@endif</div><div class="flex flex-wrap gap-2">@if($canApprove&&$request->status==='PENDING')<form method="POST" action="{{ route('jmv.requests.approve',$request) }}">@csrf<input type="hidden" name="approval_remarks" value="Approved"><button class="rounded-xl border-0 bg-blue-700 px-4 py-2 text-sm font-bold text-white">Approve</button></form><button data-bs-toggle="modal" data-bs-target="#reject{{ $request->id }}" class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-2 text-sm font-bold text-rose-700">Return</button>@endif @if($canRelease&&$request->status==='APPROVED')<form method="POST" action="{{ route('jmv.requests.release',$request) }}">@csrf<button class="rounded-xl border-0 bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Release Stock</button></form>@endif</div></div></article>
<div class="modal fade" id="reject{{ $request->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{ route('jmv.requests.reject',$request) }}" class="modal-content rounded-4 border-0">@csrf<div class="modal-header"><h2 class="modal-title fs-5 fw-bold">Return Request</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label fw-bold">Reason *</label><textarea name="approval_remarks" required maxlength="2000" rows="4" class="form-control"></textarea></div><div class="modal-footer"><button class="btn btn-danger">Return Request</button></div></form></div></div>
@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center text-slate-500">No stock requests found.</div>@endforelse</div><div class="mt-4">{{ $requests->links() }}</div>
</div></section>
@if($canCreate)<div class="modal fade" id="requestModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form method="POST" action="{{ route('jmv.requests.store') }}" class="modal-content rounded-4 border-0">@csrf<div class="modal-header"><h2 class="modal-title fs-5 fw-bold">New Stock Request</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="vstack gap-3"><div><label class="form-label fw-bold">Item *</label><select name="item_id" required class="form-select"><option value="">Select item</option>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->item_code }} — {{ $item->item_name }} ({{ $item->stock_on_hand }})</option>@endforeach</select></div><div><label class="form-label fw-bold">Location *</label><select name="location_id" required class="form-select">@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select></div><div><label class="form-label fw-bold">Quantity *</label><input type="number" name="quantity" min="1" required class="form-control"></div><div><label class="form-label fw-bold">Purpose *</label><textarea name="purpose" required maxlength="1000" rows="3" class="form-control"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Submit Request</button></div></form></div></div>@endif
@endsection
