@extends('layouts.app')

@section('title', 'HYVE Dashboard | Villa Group')

@section('content')
<section class="min-h-[calc(100svh-74px)] bg-gradient-to-br from-slate-950 via-slate-900 to-violet-950 px-4 py-6 text-white sm:px-7 lg:px-12"><div class="mx-auto max-w-7xl"><header class="mb-6"><p class="mb-1 text-xs font-extrabold uppercase tracking-[.16em] text-violet-300">HYVE</p><h1 class="m-0 text-2xl font-black sm:text-3xl">Booking Dashboard</h1><p class="mt-1 text-sm text-slate-300">Booking activity, confirmations and verified revenue.</p></header>
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Bookings',$metrics['totalBookings'],'bi-calendar2-week'],['Confirmed',$metrics['confirmedBookings'],'bi-calendar2-check'],['Pending',$metrics['pendingBookings'],'bi-hourglass-split'],['Verified Revenue','₱'.number_format($metrics['totalRevenue'],2),'bi-cash-stack']] as [$label,$value,$icon])<article class="rounded-2xl border border-white/10 bg-white/10 p-5 shadow-xl backdrop-blur"><span class="mb-4 grid h-11 w-11 place-items-center rounded-xl bg-violet-400/15 text-lg text-violet-200"><i class="bi {{ $icon }}"></i></span><p class="mb-1 text-xs font-extrabold uppercase tracking-wider text-slate-300">{{ $label }}</p><p class="mb-0 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>
<article class="mt-5 rounded-2xl border border-white/10 bg-white/10 p-6 backdrop-blur"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="mb-1 text-lg font-black">Reservation overview</h2><p class="mb-0 text-sm text-slate-300">{{ $metrics['pendingBookings'] }} booking(s) await review or verification.</p></div>@if(auth()->user()->role !== 'owner')<a href="{{ route('hyve.projects.index') }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-extrabold text-slate-900 no-underline"><i class="bi bi-arrow-right"></i>Open bookings</a>@else<span class="inline-flex rounded-full bg-white/10 px-3 py-2 text-xs font-extrabold text-violet-200"><i class="bi bi-eye mr-1"></i>Read-only dashboard</span>@endif</div></article></div></section>
@endsection
