@php
    $fieldClass = 'h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-villa-500 focus:ring-4 focus:ring-villa-100';
    $editing = isset($user) && $user;
@endphp
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">First Name</span><input type="text" name="name" value="{{ old('name', $user?->name) }}" class="{{ $fieldClass }}" autocomplete="given-name" required></label>
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Last Name</span><input type="text" name="lastname" value="{{ old('lastname', $user?->lastname) }}" class="{{ $fieldClass }}" autocomplete="family-name" required></label>
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Username</span><input type="text" name="username" value="{{ old('username', $user?->username) }}" class="{{ $fieldClass }}" autocomplete="off" required></label>
<label class="block sm:col-span-2"><span class="mb-2 block text-sm font-bold text-slate-700">Email Address</span><input type="email" name="email" value="{{ old('email', $user?->email) }}" class="{{ $fieldClass }}" autocomplete="email" required></label>
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Contact Number</span><input type="tel" name="cell_number" value="{{ old('cell_number', $user?->cell_number) }}" class="{{ $fieldClass }}" autocomplete="tel" required></label>
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Company</span><select id="divisionSelect" name="division_id" class="{{ $fieldClass }}" required><option value="">Select company</option>@foreach($divisions as $division)<option value="{{ $division->id }}" data-name="{{ strtolower($division->name) }}" @selected((string) old('division_id', $user?->division_id) === (string) $division->id)>{{ $division->name }}</option>@endforeach</select></label>
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Department</span><select id="departmentSelect" name="department_id" class="{{ $fieldClass }}" required><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}" data-division="{{ $department->division_id }}" data-name="{{ strtolower($department->name) }}" @selected((string) old('department_id', $user?->department_id) === (string) $department->id)>{{ $department->name }}</option>@endforeach</select><span class="mt-1.5 block text-xs text-slate-500">Departments are filtered by the selected company.</span></label>
<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Position</span><select id="positionSelect" name="position_id" class="{{ $fieldClass }}" required><option value="">Select position</option>@foreach($positions as $position)<option value="{{ $position->id }}" data-division="{{ $position->division_id }}" data-department="{{ $position->department_id }}" data-code="{{ $position->code }}" @selected((string) old('position_id', $user?->position_id) === (string) $position->id)>{{ $position->name }}</option>@endforeach</select><span class="mt-1.5 block text-xs text-slate-500">Positions are filtered by company and department.</span></label>
<label class="block sm:col-span-2"><span class="mb-2 block text-sm font-bold text-slate-700">System Access Profile</span><select id="accessRoleSelect" name="access_role_id" class="{{ $fieldClass }}" required><option value="">Select access profile</option>@foreach($roles as $accessRole)<option value="{{ $accessRole->id }}" data-slug="{{ $accessRole->slug }}" data-description="{{ $accessRole->description }}" @selected((string) old('access_role_id', $user?->access_role_id) === (string) $accessRole->id)>{{ $accessRole->name }}</option>@endforeach</select><span id="accessRoleHelp" class="mt-1.5 block text-xs text-slate-500">Access controls are separate from the employee's job position.</span></label>
@if($editing)<label class="block"><span class="mb-2 block text-sm font-bold text-slate-700">Account Status</span><select name="status" class="{{ $fieldClass }}" required @disabled(auth()->id() === $user->id)><option value="1" @selected((string) old('status', (int) $user->status) === '1')>Active</option><option value="0" @selected((string) old('status', (int) $user->status) === '0')>Inactive</option></select>@if(auth()->id() === $user->id)<input type="hidden" name="status" value="1"><span class="mt-1.5 block text-xs text-slate-500">You cannot deactivate your own account.</span>@endif</label>@endif
@php($selectedVessels = collect(old('vessel_ids', $user?->vesselAssignments?->where('is_active', true)->pluck('vessel_id')->all() ?? []))->map(fn ($id) => (int) $id))
<fieldset id="vesselAssignmentFields" class="hidden sm:col-span-2 lg:col-span-3 rounded-2xl border border-sky-200 bg-sky-50/70 p-5">
    <input type="hidden" name="vessel_assignment_present" value="1">
    <legend class="px-2 text-sm font-extrabold text-sky-950">Vessel Assignment</legend>
    <p class="mb-4 text-xs leading-5 text-sky-700">This employee will see only the selected vessels across Vessel Management, voyage and fuel records, Technical &amp; Defect, Certificates, and Dry Docking.</p>
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        @forelse($vessels as $vessel)
            <label class="flex cursor-pointer items-center gap-3 rounded-xl border border-sky-100 bg-white px-4 py-3 shadow-sm transition hover:border-sky-300"><input type="checkbox" name="vessel_ids[]" value="{{ $vessel->id }}" class="h-4 w-4 accent-sky-700" @checked($selectedVessels->contains((int) $vessel->id))><span class="text-sm font-bold text-slate-700">{{ $vessel->vessel_name }}</span></label>
        @empty
            <p class="text-sm text-slate-500">No vessels are available yet. The account can be assigned later.</p>
        @endforelse
    </div>
</fieldset>
@php($selectedApprovals = collect(old('approval_modules', $user?->approvalAuthorities?->where('is_active',true)->pluck('module')->all() ?? [])))
<fieldset id="approvalAuthorityFields" class="hidden sm:col-span-2 lg:col-span-3 rounded-2xl border border-violet-200 bg-violet-50/70 p-5"><legend class="px-2 text-sm font-extrabold text-violet-950">Approval Authority</legend><p class="mb-4 text-xs leading-5 text-violet-700">Select only the workflows this employee is formally authorized to approve. The Company Approver access profile and a supported company workflow are both required.</p><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($approvalModules as $module => $label)<label data-approval-module="{{ $module }}" class="hidden cursor-pointer items-center gap-3 rounded-xl border border-violet-100 bg-white px-4 py-3"><input type="checkbox" name="approval_modules[]" value="{{ $module }}" class="h-4 w-4 accent-violet-700" @checked($selectedApprovals->contains($module))><span class="text-sm font-bold text-slate-700">{{ $label }}</span></label>@endforeach</div></fieldset>
