@php($current=$editingItem)
<div class="col-md-8"><label class="form-label fw-bold">Item Name *</label><input name="item_name" class="form-control" required maxlength="255" value="{{ old('item_name',$current?->item_name) }}"></div>
<div class="col-md-4"><label class="form-label fw-bold">Unit *</label><input name="unit" class="form-control" required maxlength="50" placeholder="pcs, kg, liters" value="{{ old('unit',$current?->unit) }}"></div>
<div class="col-12"><label class="form-label fw-bold">Description</label><textarea name="description" class="form-control" rows="2" maxlength="3000">{{ old('description',$current?->description) }}</textarea></div>
<div class="col-md-6"><label class="form-label fw-bold">Category *</label><select name="category_id" class="form-select" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$current?->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label fw-bold">Default Location *</label><select name="default_location_id" class="form-select" required><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('default_location_id',$current?->default_location_id)==$location->id)>{{ $location->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label fw-bold">Minimum Level *</label><input type="number" min="0" name="minimum_quantity" class="form-control" required value="{{ old('minimum_quantity',$current?->minimum_quantity ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label fw-bold">Maximum Level *</label><input type="number" min="0" name="maximum_quantity" class="form-control" required value="{{ old('maximum_quantity',$current?->maximum_quantity ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label fw-bold">{{ $current ? 'Current Stock' : 'Opening Stock' }} *</label><input type="number" min="0" name="stock_on_hand" class="form-control" required {{ $current ? 'readonly' : '' }} value="{{ old('stock_on_hand',$current?->stock_on_hand ?? 0) }}"><small class="text-muted">{{ $current ? 'Use an adjustment to correct stock.' : 'Creates an opening-balance transaction.' }}</small></div>
<div class="col-md-6"><label class="form-label fw-bold">Unit Cost</label><input type="number" min="0" step="0.01" name="unit_cost" class="form-control" value="{{ old('unit_cost',$current?->unit_cost) }}"></div>
<div class="col-md-6"><label class="form-label fw-bold">Preferred Supplier</label><input name="preferred_supplier" maxlength="255" class="form-control" value="{{ old('preferred_supplier',$current?->preferred_supplier) }}"></div>
@if($current)<div class="col-12"><label class="form-label fw-bold">Status</label><select name="status" class="form-select"><option value="1" @selected(old('status',$current->status)==1)>Active</option><option value="0" @selected(old('status',$current->status)==0)>Inactive</option></select></div>@endif
