@extends('layouts.app')
@section('title', ($type === 'IN' ? 'Stock In' : 'Stock Out').' | JMV')
@section('content')
@php($isStockIn=$type==='IN')
<section class="min-h-[calc(100svh-74px)] bg-slate-50 px-4 py-6 sm:px-7 lg:px-10"><div class="mx-auto max-w-7xl">
@if(session('success'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<header class="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-extrabold uppercase tracking-[.16em] {{ $isStockIn?'text-emerald-700':'text-rose-700' }}">JMV Inventory Movement</p><h1 class="m-0 text-2xl font-black text-slate-900 sm:text-3xl">{{ $isStockIn?'Stock In':'Stock Out' }}</h1><p class="mt-1 text-sm text-slate-500">{{ $isStockIn?'Receive materials with source and delivery documentation.':'Issue materials with accountable recipient and purpose.' }}</p></div>@if($canManage)<button data-bs-toggle="modal" data-bs-target="#movementModal" class="inline-flex min-h-11 items-center gap-2 rounded-xl border-0 px-4 text-sm font-extrabold text-white shadow-sm {{ $isStockIn?'bg-emerald-700':'bg-rose-700' }}"><i class="bi bi-plus-lg"></i>Record {{ $isStockIn?'Receipt':'Issuance' }}</button>@endif</header>

<form method="GET" class="mb-4 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_1fr_auto]"><select name="item_id" class="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="">All items</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(request('item_id')==$item->id)>{{ $item->item_code }} — {{ $item->item_name }}</option>@endforeach</select><select name="location_id" class="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><option value="">All locations</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(request('location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select><button class="min-h-11 rounded-xl border-0 bg-slate-900 px-5 text-sm font-bold text-white">Filter</button></form>

<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[1120px] text-left text-sm"><thead class="bg-slate-900 text-xs uppercase tracking-wider text-white"><tr><th class="px-4 py-4">Date / Reference</th><th class="px-4 py-4">Item</th><th class="px-4 py-4">Location</th><th class="px-4 py-4">Quantity</th><th class="px-4 py-4">Balance</th><th class="px-4 py-4">{{ $isStockIn?'Supplier':'Recipient / Purpose' }}</th><th class="px-4 py-4">Recorded By</th><th class="px-4 py-4">Proof</th>@if($canAdjust)<th class="px-4 py-4">Control</th>@endif</tr></thead><tbody class="divide-y divide-slate-100">
@forelse($movements as $movement)<tr class="hover:bg-slate-50"><td class="px-4 py-4"><strong class="block text-slate-800">{{ optional($movement->transacted_at)->format('M d, Y h:i A') }}</strong><span class="text-xs text-slate-500">{{ $movement->reference_no }}</span><span class="ml-2 rounded bg-slate-100 px-2 py-1 text-[.65rem] font-bold text-slate-600">{{ $movement->movement_kind }}</span></td><td class="px-4 py-4"><strong>{{ $movement->item?->item_name ?? 'Unavailable item' }}</strong><span class="block text-xs text-amber-700">{{ $movement->item?->item_code }}</span></td><td class="px-4 py-4">{{ $movement->location?->name ?? 'Legacy location' }}</td><td class="px-4 py-4 font-black {{ $isStockIn?'text-emerald-700':'text-rose-700' }}">{{ $isStockIn?'+':'−' }}{{ number_format($movement->quantity) }}</td><td class="px-4 py-4 text-xs text-slate-600">{{ number_format($movement->balance_before) }} → <strong>{{ number_format($movement->balance_after) }}</strong></td><td class="px-4 py-4">@if($isStockIn){{ $movement->supplier_name ?: '—' }}@else<strong class="block">{{ $movement->issued_to ?: '—' }}</strong><span class="text-xs text-slate-500">{{ $movement->purpose ?: $movement->remarks }}</span>@endif</td><td class="px-4 py-4">{{ trim(($movement->user?->name??'').' '.($movement->user?->lastname??'')) ?: 'N/A' }}</td><td class="px-4 py-4">@if($movement->attachment_path)<a class="font-bold text-blue-700" href="{{ route('jmv.transactions.attachment',$movement) }}"><i class="bi bi-paperclip"></i>View</a>@else<span class="text-slate-400">—</span>@endif</td>@if($canAdjust)<td class="px-4 py-4">@if($movement->movement_kind!=='REVERSAL' && !$movement->reversal_of_id)<button data-bs-toggle="modal" data-bs-target="#reverse{{ $movement->id }}" class="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">Reverse</button>@endif</td>@endif</tr>
@empty<tr><td colspan="9" class="px-6 py-14 text-center text-slate-500">No {{ strtolower($isStockIn?'stock in':'stock out') }} transactions found.</td></tr>@endforelse
</tbody></table></div><div class="border-t border-slate-100 p-4">{{ $movements->links() }}</div></div>
</div></section>

@if($canAdjust)
    @foreach($movements as $movement)
        @if($movement->movement_kind !== 'REVERSAL' && !$movement->reversal_of_id)
        <div class="modal fade" id="reverse{{ $movement->id }}" tabindex="-1" aria-labelledby="reverseTitle{{ $movement->id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered px-2">
                <form method="POST" action="{{ route('jmv.transactions.reverse', $movement) }}" class="modal-content overflow-hidden rounded-4 border-0 shadow-lg">
                    @csrf
                    <div class="modal-header border-bottom px-4 py-3">
                        <div>
                            <p class="mb-1 text-xs font-extrabold uppercase tracking-wider text-rose-600">Inventory Correction</p>
                            <h2 class="modal-title fs-5 fw-bold text-slate-900" id="reverseTitle{{ $movement->id }}">Reverse Transaction</h2>
                        </div>
                        <button type="button" class="btn-close rounded-3 border border-slate-200 p-2" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body px-4 py-4">
                        <div class="mb-4 rounded-3 border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">
                            <strong class="d-block mb-1">{{ $movement->reference_no }} · {{ $movement->item?->item_name }}</strong>
                            A linked opposite transaction will be created. The original history will remain permanent.
                        </div>
                        <label for="reverseReason{{ $movement->id }}" class="form-label fw-bold text-slate-800">Reason for reversal <span class="text-danger">*</span></label>
                        <textarea id="reverseReason{{ $movement->id }}" name="reason" required maxlength="2000" rows="4" class="form-control rounded-3" placeholder="Explain why this transaction must be reversed..."></textarea>
                        <div class="form-text">This reason will be stored in the permanent audit trail.</div>
                    </div>
                    <div class="modal-footer flex-column-reverse gap-2 border-top bg-slate-50 px-4 py-3 sm:flex-row sm:justify-end">
                        <button type="button" class="btn btn-light w-100 rounded-3 border sm:w-auto" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger w-100 rounded-3 px-4 sm:w-auto"><i class="bi bi-arrow-counterclockwise me-2"></i>Confirm Reversal</button>
                    </div>
                </form>
            </div>
        </div>
        @endif
    @endforeach
@endif

@if($canManage)<div class="modal fade" id="movementModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable"><form method="POST" enctype="multipart/form-data" action="{{ route($isStockIn?'jmv.stockin.store':'jmv.stockout.store') }}" class="modal-content rounded-4 border-0">@csrf<div class="modal-header"><div><h2 class="modal-title fs-5 fw-bold">Record {{ $isStockIn?'Stock Receipt':'Stock Issuance' }}</h2><small class="text-muted">Posted records are corrected through reversal, never deletion.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-md-8"><label class="form-label fw-bold">Item *</label><select name="item_id" required class="form-select"><option value="">Select item</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old('item_id')==$item->id)>{{ $item->item_code }} — {{ $item->item_name }} ({{ $item->stock_on_hand }} {{ $item->unit }})</option>@endforeach</select></div><div class="col-md-4"><label class="form-label fw-bold">Quantity *</label><input type="number" min="1" name="quantity" required class="form-control" value="{{ old('quantity') }}"></div>
<div class="col-md-6"><label class="form-label fw-bold">Location *</label><select name="location_id" required class="form-select"><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label fw-bold">Reference Number *</label><input name="reference_no" required maxlength="100" class="form-control" value="{{ old('reference_no') }}"></div>
@if($isStockIn)<div class="col-md-8"><label class="form-label fw-bold">Supplier / Source *</label><input name="supplier_name" required maxlength="255" class="form-control" value="{{ old('supplier_name') }}"></div><div class="col-md-4"><label class="form-label fw-bold">Unit Cost</label><input type="number" min="0" step="0.01" name="unit_cost" class="form-control" value="{{ old('unit_cost') }}"></div>@else<div class="col-md-6"><label class="form-label fw-bold">Issued To *</label><input name="issued_to" required maxlength="255" class="form-control" value="{{ old('issued_to') }}"></div><div class="col-md-6"><label class="form-label fw-bold">Department</label><select name="department_id" class="form-select"><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id')==$department->id)>{{ $department->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label fw-bold">Project / Equipment</label><input name="project_equipment" maxlength="255" class="form-control" value="{{ old('project_equipment') }}"></div><div class="col-md-6"><label class="form-label fw-bold">Purpose *</label><input name="purpose" required maxlength="1000" class="form-control" value="{{ old('purpose') }}"></div>@endif
<div class="col-md-6"><label class="form-label fw-bold">Date and Time *</label><input type="datetime-local" name="transacted_at" required class="form-control" value="{{ old('transacted_at',now()->format('Y-m-d\TH:i')) }}"></div><div class="col-md-6"><label class="form-label fw-bold">Supporting Document</label><input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png" class="form-control"><small class="text-muted">PDF, JPG or PNG. Maximum 5 MB.</small></div><div class="col-12"><label class="form-label fw-bold">Remarks</label><textarea name="remarks" maxlength="2000" rows="3" class="form-control">{{ old('remarks') }}</textarea></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn {{ $isStockIn?'btn-success':'btn-danger' }}">Post {{ $isStockIn?'Receipt':'Issuance' }}</button></div></form></div></div>@endif
@endsection
