@php
$fullName = fn($user) => $user ? trim($user->name.' '.$user->lastname) : '—';
$dateTime = fn($value) => $value ? $value->format('M d, Y g:i A') : '—';
$date = fn($value) => $value ? $value->format('M d, Y') : '—';
$beforePhotos = $report->attachments->where('category', 'Before Repair')->filter(fn($file) => isset($pdfImageData[$file->id]));
$afterPhotos = $report->attachments->where('category', 'After Repair')->filter(fn($file) => isset($pdfImageData[$file->id]));
$initialFiles = $report->attachments->whereIn('category', ['Checklist', 'Before Repair']);
$closeoutFiles = $report->attachments->whereNotIn('category', ['Checklist', 'Before Repair']);
@endphp
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
@page{margin:30px 34px 42px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:9px;line-height:1.45;margin:0}.footer{position:fixed;left:0;right:0;bottom:-27px;border-top:1px solid #cbd5e1;padding-top:6px;color:#64748b;font-size:7px}.footer .right{float:right}.brand{border-bottom:4px solid #24477f;padding-bottom:12px;margin-bottom:14px}.brand h1{margin:0;color:#17365f;font-size:21px}.brand p{margin:3px 0 0;color:#64748b}.title-table,.details,.list,.signoff,.image-grid{width:100%;border-collapse:collapse}.title-table td{vertical-align:middle}.report-code{font-size:19px;font-weight:800;color:#172033}.status{display:inline-block;background:#e8eef7;color:#24477f;border:1px solid #c6d4e8;border-radius:12px;padding:4px 9px;font-weight:bold}.section{margin-top:12px;page-break-inside:avoid}.section-title{background:#24477f;color:#fff;padding:7px 9px;font-size:11px;font-weight:bold;border-radius:5px 5px 0 0}.details td,.list th,.list td,.signoff td{border:1px solid #dbe2ea;padding:6px;vertical-align:top}.details td{width:25%}.label{display:block;color:#64748b;text-transform:uppercase;font-size:7px;font-weight:bold;letter-spacing:.4px;margin-bottom:2px}.value{font-weight:bold;color:#172033}.text-box{border:1px solid #dbe2ea;border-top:0;padding:8px;white-space:pre-wrap}.subsection{font-weight:bold;color:#24477f;margin:8px 0 4px}.list th{background:#eef3f9;color:#24477f;text-transform:uppercase;font-size:7px}.muted{color:#64748b}.image-grid td{width:50%;padding:5px;vertical-align:top}.photo{border:1px solid #dbe2ea;padding:5px;page-break-inside:avoid}.photo img{display:block;width:100%;max-height:220px;object-fit:contain}.photo-name{margin-top:4px;font-size:7px;color:#475569}.page-break{page-break-before:always}.empty{padding:8px;border:1px solid #dbe2ea;color:#64748b}.money{text-align:right}.audit-action{text-transform:capitalize}.nowrap{white-space:nowrap}
</style>
</head>
<body>
<div class="footer"><span>Villa Shipping Lines · Controlled Technical Defect Record · {{ $report->report_code }}</span><span class="right">Generated {{ now()->format('M d, Y g:i A') }}</span></div>

<div class="brand"><h1>VILLA SHIPPING LINES</h1><p>Technical Defect Monitoring and Corrective Action Report</p></div>
<table class="title-table"><tr><td><div class="report-code">{{ $report->report_code }}</div><span class="muted">Created {{ $dateTime($report->created_at) }}</span></td><td style="text-align:right"><span class="status">{{ strtoupper($report->status) }}</span></td></tr></table>

<div class="section"><div class="section-title">1. Report Identification and Accountability</div><table class="details">
<tr><td><span class="label">Vessel</span><span class="value">{{ $report->vessel?->vessel_name ?: '—' }}</span></td><td><span class="label">Date identified</span><span class="value">{{ $date($report->date_identified) }}</span></td><td><span class="label">Port / location</span><span class="value">{{ $report->port_location ?: '—' }}</span></td><td><span class="label">System affected</span><span class="value">{{ $report->system_affected ?: '—' }}</span></td></tr>
<tr><td><span class="label">Reported by</span><span class="value">{{ $fullName($report->reporter) }}</span></td><td><span class="label">Reporter position</span><span class="value">{{ $report->reporter?->position?->name ?: '—' }}</span></td><td><span class="label">Assigned PIC</span><span class="value">{{ $fullName($report->assignee) }}</span></td><td><span class="label">PIC position</span><span class="value">{{ $report->assignee?->position?->name ?: '—' }}</span></td></tr>
<tr><td><span class="label">Severity</span><span class="value">{{ $report->severity_level ?: '—' }}</span></td><td><span class="label">Operational impact</span><span class="value">{{ $report->operational_impact ?: '—' }}</span></td><td><span class="label">Temporary repair</span><span class="value">{{ $report->temporary_repair ?: '—' }}</span></td><td><span class="label">Target completion</span><span class="value">{{ $date($report->target_completion_date) }}</span></td></tr>
</table></div>

<div class="section"><div class="section-title">2. Initial Defect Report</div><div class="text-box"><span class="label">Defect description</span>{{ $report->defect_description ?: 'Not provided' }}</div><div class="text-box"><span class="label">Initial cause / observation</span>{{ $report->initial_cause ?: 'Not provided' }}</div><div class="text-box"><span class="label">Initial remarks</span>{{ $report->remarks ?: 'Not provided' }}</div></div>

<div class="section"><div class="section-title">3. Initial Attachments and Affected Defect Photos</div>
@if($initialFiles->isNotEmpty())<table class="list"><thead><tr><th>Category</th><th>File</th><th>Uploaded by</th><th>Date</th><th>Size</th></tr></thead><tbody>@foreach($initialFiles as $file)<tr><td>{{ $file->category }}</td><td>{{ $file->original_name }}</td><td>{{ $fullName($file->uploader) }}</td><td class="nowrap">{{ $dateTime($file->created_at) }}</td><td>{{ number_format($file->size / 1024, 1) }} KB</td></tr>@endforeach</tbody></table>@else<div class="empty">No initial attachments recorded.</div>@endif
@if($beforePhotos->isNotEmpty())<div class="subsection">Affected defect photo evidence</div><table class="image-grid">@foreach($beforePhotos->chunk(2) as $row)<tr>@foreach($row as $file)<td><div class="photo"><img src="{{ $pdfImageData[$file->id] }}" alt="Affected defect"><div class="photo-name">{{ $file->original_name }} · {{ $dateTime($file->created_at) }}</div></div></td>@endforeach @if($row->count()===1)<td></td>@endif</tr>@endforeach</table>@endif
</div>

<div class="section"><div class="section-title">4. Management Review and Technical Assessment</div><table class="details"><tr><td><span class="label">Submitted for review by</span><span class="value">{{ $fullName($report->reviewSubmitter) }}</span><br><span class="muted">{{ $dateTime($report->review_submitted_at) }}</span></td><td><span class="label">Reviewed by</span><span class="value">{{ $fullName($report->reviewer) }}</span><br><span class="muted">{{ $dateTime($report->reviewed_at) }}</span></td><td><span class="label">Assessed by</span><span class="value">{{ $fullName($report->assessor) }}</span><br><span class="muted">{{ $dateTime($report->assessed_at) }}</span></td><td><span class="label">Action assigned by</span><span class="value">{{ $fullName($report->actionAssigner) }}</span><br><span class="muted">{{ $dateTime($report->action_assigned_at) }}</span></td></tr></table>
@foreach([['Management review remarks',$report->review_remarks],['Technical assessment',$report->technical_assessment],['Technical findings',$report->technical_findings],['Technical recommendation',$report->technical_recommendation]] as [$label,$value])<div class="text-box"><span class="label">{{ $label }}</span>{{ $value ?: 'Not provided' }}</div>@endforeach
</div>

@if($report->informationRequests->isNotEmpty())<div class="section"><div class="section-title">5. Additional Information Requests</div><table class="list"><thead><tr><th>Requested</th><th>Request</th><th>Response</th><th>Status</th></tr></thead><tbody>@foreach($report->informationRequests->sortBy('requested_at') as $request)<tr><td>{{ $fullName($request->requester) }}<br><span class="muted">{{ $dateTime($request->requested_at) }}</span></td><td>{{ $request->request_text }}</td><td>{{ $request->response_text ?: 'Pending response' }}@if($request->response_text)<br><span class="muted">{{ $fullName($request->responder) }} · {{ $dateTime($request->responded_at) }}</span>@endif</td><td>{{ $request->status }}</td></tr>@endforeach</tbody></table></div>@endif

<div class="section"><div class="section-title">{{ $report->informationRequests->isNotEmpty() ? '6' : '5' }}. Corrective Action, Progress and Downtime</div><table class="details"><tr><td><span class="label">Progress</span><span class="value">{{ (int)$report->progress_percent }}%</span></td><td><span class="label">Last updated by</span><span class="value">{{ $fullName($report->progressUpdater) }}</span></td><td><span class="label">Progress updated</span><span class="value">{{ $dateTime($report->progress_updated_at) }}</span></td><td><span class="label">Total downtime</span><span class="value">{{ $report->total_downtime_hours !== null ? $report->total_downtime_hours.' hrs' : '—' }}</span></td></tr><tr><td colspan="2"><span class="label">Downtime started</span><span class="value">{{ $dateTime($report->downtime_started_at) }}</span></td><td colspan="2"><span class="label">Downtime ended</span><span class="value">{{ $dateTime($report->downtime_ended_at) }}</span></td></tr></table>
@foreach([['Latest progress update',$report->progress_notes],['Root cause analysis',$report->root_cause],['Corrective action',$report->corrective_action],['Preventive action',$report->preventive_action]] as [$label,$value])<div class="text-box"><span class="label">{{ $label }}</span>{{ $value ?: 'Not provided' }}</div>@endforeach
</div>

<div class="section"><div class="section-title">Cost Accountability</div><table class="details"><tr><td><span class="label">Report completion cost</span><span class="value">PHP {{ number_format((float)$report->completion_cost,2) }}</span></td><td><span class="label">Third-party actual cost</span><span class="value">PHP {{ number_format((float)$report->supports->sum('actual_cost'),2) }}</span></td><td colspan="2"><span class="label">Total recorded cost</span><span class="value">PHP {{ number_format((float)$report->completion_cost + (float)$report->supports->sum('actual_cost'),2) }}</span></td></tr></table></div><div class="section"><div class="section-title">Third-Party Support and Cost Accountability</div>@forelse($report->supports as $support)<table class="details" style="margin-bottom:7px"><tr><td colspan="2"><span class="label">Vendor</span><span class="value">{{ $support->vendor_name }}</span></td><td><span class="label">Status</span><span class="value">{{ $support->status }}</span></td><td><span class="label">Expected completion</span><span class="value">{{ $date($support->expected_completion_date) }}</span></td></tr><tr><td colspan="2"><span class="label">Scope / reason</span>{{ $support->reason_for_support }}</td><td><span class="label">Contact</span>{{ $support->contact_person ?: '—' }}<br>{{ $support->contact_number ?: '' }}</td><td><span class="label">Spares / tools</span>{{ $support->spares_required ?: '—' }} / {{ $support->tools_required ?: '—' }}</td></tr><tr><td><span class="label">Quoted cost</span><span class="value">PHP {{ number_format((float)$support->quoted_cost,2) }}</span></td><td><span class="label">Actual cost</span><span class="value">{{ $support->actual_cost !== null ? 'PHP '.number_format((float)$support->actual_cost,2) : 'Pending' }}</span></td><td><span class="label">Assigned by</span>{{ $fullName($support->creator) }}</td><td><span class="label">Completed by / at</span>{{ $fullName($support->completer) }}<br><span class="muted">{{ $dateTime($support->completed_at) }}</span></td></tr></table>@empty<div class="empty">No third-party support was recorded.</div>@endforelse</div>

<div class="section"><div class="section-title">Repair Evidence and Supporting Documents</div>@if($closeoutFiles->isNotEmpty())<table class="list"><thead><tr><th>Category</th><th>File</th><th>Uploaded by</th><th>Date</th><th>Size</th></tr></thead><tbody>@foreach($closeoutFiles as $file)<tr><td>{{ $file->category }}</td><td>{{ $file->original_name }}</td><td>{{ $fullName($file->uploader) }}</td><td class="nowrap">{{ $dateTime($file->created_at) }}</td><td>{{ number_format($file->size / 1024, 1) }} KB</td></tr>@endforeach</tbody></table>@else<div class="empty">No repair evidence or supporting documents recorded.</div>@endif
@if($afterPhotos->isNotEmpty())<div class="subsection">After-repair photo evidence</div><table class="image-grid">@foreach($afterPhotos->chunk(2) as $row)<tr>@foreach($row as $file)<td><div class="photo"><img src="{{ $pdfImageData[$file->id] }}" alt="After repair"><div class="photo-name">{{ $file->original_name }} · {{ $dateTime($file->created_at) }}</div></div></td>@endforeach @if($row->count()===1)<td></td>@endif</tr>@endforeach</table>@endif
</div>

<div class="section"><div class="section-title">Verification and Final Closure</div><table class="signoff"><tr><td><span class="label">Repair submitted by</span><span class="value">{{ $fullName($report->repairCompleter) }}</span><br><span class="muted">{{ $dateTime($report->repair_completed_at) }}</span></td><td><span class="label">Resolution verified by</span><span class="value">{{ $fullName($report->verifier) }}</span><br><span class="muted">{{ $dateTime($report->verified_at) }}</span></td><td><span class="label">Report closed by</span><span class="value">{{ $fullName($report->closer) }}</span><br><span class="muted">{{ $dateTime($report->closed_at) }}</span></td></tr></table><div class="text-box"><span class="label">Verification remarks</span>{{ $report->verification_remarks ?: 'Not provided' }}</div></div>

<div class="section page-break"><div class="section-title">Complete Audit Trail</div><table class="list"><thead><tr><th>Date and time</th><th>Action</th><th>Actor</th><th>Status movement</th><th>Description</th></tr></thead><tbody>@forelse($report->audits->sortBy('created_at') as $audit)<tr><td class="nowrap">{{ $dateTime($audit->created_at) }}</td><td class="audit-action">{{ str_replace('_',' ',$audit->action) }}</td><td>{{ $fullName($audit->user) }}</td><td>{{ $audit->from_status ?: '—' }} → {{ $audit->to_status ?: '—' }}</td><td>{{ $audit->description ?: '—' }}</td></tr>@empty<tr><td colspan="5">No audit entries recorded.</td></tr>@endforelse</tbody></table></div>
</body>
</html>
