@extends('layouts.app')

@section('title', $consumable->item_name.' | Consumables')

@section('content')
<main class="mx-auto w-full max-w-6xl px-4 py-6 sm:px-6 lg:py-8">
    <a href="{{ route('yatira.inventory.index', ['tab' => 'consumables']) }}" class="mb-4 inline-flex items-center gap-2 text-sm font-bold text-villa-700 no-underline"><i class="bi bi-arrow-left"></i> Back to consumables</a>
    @if(session('success'))<div class="mb-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><strong>Please correct the following:</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <header class="mb-5 rounded-3xl bg-gradient-to-r from-villa-900 to-villa-700 p-6 text-white shadow-xl sm:p-8"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-extrabold uppercase tracking-[.18em] text-amber-200">{{ $consumable->item_code }}</p><h1 class="mb-1 text-2xl font-black sm:text-3xl">{{ $consumable->item_name }}</h1><p class="mb-0 text-sm text-blue-100">Tracked in {{ $consumable->unit }}</p></div><div class="rounded-2xl bg-white/10 px-5 py-3 text-right ring-1 ring-white/20"><p class="mb-0 text-xs font-bold uppercase text-blue-100">Stock on hand</p><p class="mb-0 text-3xl font-black">{{ number_format($consumable->stock_on_hand) }}</p></div></div></header>

    <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
        <section class="rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="mb-1 text-lg font-black text-slate-900">Movement history</h2><p class="mb-0 text-sm text-slate-500">Immutable stock balance trail with references and responsible users.</p></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Type</th><th class="px-5 py-3">Quantity</th><th class="px-5 py-3">Balance</th><th class="px-5 py-3">Reference</th><th class="px-5 py-3">Recorded by</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($transactions as $transaction)<tr><td class="whitespace-nowrap px-5 py-4">{{ optional($transaction->transacted_at)->format('M d, Y h:i A') }}</td><td class="px-5 py-4 font-black {{ $transaction->type === 'OUT' ? 'text-rose-700' : ($transaction->type === 'IN' ? 'text-emerald-700' : 'text-amber-700') }}">{{ $transaction->type }}</td><td class="px-5 py-4">{{ number_format($transaction->quantity) }}</td><td class="whitespace-nowrap px-5 py-4">{{ number_format($transaction->balance_before) }} &rarr; {{ number_format($transaction->balance_after) }}</td><td class="px-5 py-4"><strong>{{ $transaction->reference_no }}</strong>@if($transaction->remarks)<div class="mt-1 text-xs text-slate-500">{{ $transaction->remarks }}</div>@endif</td><td class="whitespace-nowrap px-5 py-4">{{ $transaction->user?->name ?? 'System' }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">No stock movement has been recorded.</td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $transactions->links() }}</div></section>

        <aside class="space-y-5">
            <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-base font-black text-slate-900">Item controls</h2><dl class="grid grid-cols-2 gap-3 text-sm"><div><dt class="text-xs font-bold uppercase text-slate-400">Reorder level</dt><dd class="mb-0 mt-1 font-black">{{ number_format($consumable->reorder_level) }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Status</dt><dd class="mb-0 mt-1 font-black">{{ $consumable->status ? 'Active' : 'Inactive' }}</dd></div></dl></section>
            @if($canManageConsumables)
            <details open class="rounded-3xl border border-slate-200 bg-white shadow-sm"><summary class="cursor-pointer list-none p-5 font-black text-slate-900">Record movement</summary><form method="POST" action="{{ route('yatira.inventory.consumables.movement', $consumable) }}" class="space-y-3 border-t border-slate-100 p-5">@csrf<div><label class="form-label">Movement</label><select id="movementType" name="type" class="form-select" required><option value="IN">Stock In</option><option value="OUT">Stock Out</option><option value="ADJUSTMENT">Balance Correction</option></select></div><div id="movementQuantity"><label class="form-label">Quantity</label><input type="number" name="quantity" min="1" class="form-control"></div><div id="adjustedBalance" class="d-none"><label class="form-label">Correct Balance</label><input type="number" name="adjusted_balance" min="0" class="form-control"></div><div><label class="form-label">Reference No.</label><input name="reference_no" maxlength="100" class="form-control" required></div><div><label class="form-label">Remarks</label><textarea name="remarks" maxlength="2000" rows="2" class="form-control"></textarea></div><button class="btn btn-primary w-100">Record Movement</button></form></details>
            <details class="rounded-3xl border border-slate-200 bg-white shadow-sm"><summary class="cursor-pointer list-none p-5 font-black text-slate-900">Edit item</summary><form method="POST" action="{{ route('yatira.inventory.consumables.update', $consumable) }}" class="space-y-3 border-t border-slate-100 p-5">@csrf @method('PUT')<div><label class="form-label">Item Name</label><input name="item_name" value="{{ old('item_name', $consumable->item_name) }}" class="form-control" required></div><div><label class="form-label">Unit</label><input name="unit" value="{{ old('unit', $consumable->unit) }}" class="form-control" required></div><div><label class="form-label">Reorder Level</label><input type="number" name="reorder_level" min="0" value="{{ old('reorder_level', $consumable->reorder_level) }}" class="form-control" required></div><div><label class="form-label">Status</label><select name="status" class="form-select"><option value="1" @selected($consumable->status)>Active</option><option value="0" @selected(! $consumable->status)>Inactive</option></select></div><button class="btn btn-outline-primary w-100">Update Item</button></form></details>
            @endif
        </aside>
    </div>
</main>
@endsection

@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('movementType');if(!type)return;const quantity=document.getElementById('movementQuantity');const adjusted=document.getElementById('adjustedBalance');const sync=()=>{const correction=type.value==='ADJUSTMENT';quantity.classList.toggle('d-none',correction);adjusted.classList.toggle('d-none',!correction);quantity.querySelector('input').required=!correction;adjusted.querySelector('input').required=correction;};type.addEventListener('change',sync);sync();});</script>
@endpush
