@php($current = $log ?? null)
<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Date <b class="text-rose-600">*</b></span><input type="date" name="log_date" max="{{ now()->format('Y-m-d') }}" value="{{ old('log_date', $current?->log_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Location <b class="text-rose-600">*</b></span><input list="productionLocations" name="location" maxlength="255" value="{{ old('location', $current?->location) }}" required placeholder="Mine Site" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Shift <b class="text-rose-600">*</b></span><input list="productionShifts" name="shift" maxlength="100" value="{{ old('shift', $current?->shift) }}" required placeholder="8:00 AM - 5:00 PM" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Leadman <b class="text-rose-600">*</b></span><input name="leadman" maxlength="255" value="{{ old('leadman', $current?->leadman) }}" required placeholder="Given Name, Family Name" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Foreman <b class="text-rose-600">*</b></span><input name="foreman" maxlength="255" value="{{ old('foreman', $current?->foreman) }}" required placeholder="Given Name, Family Name" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Total Workers <b class="text-rose-600">*</b></span><input type="number" min="1" name="total_workers" value="{{ old('total_workers', $current?->total_workers) }}" required placeholder="No." class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
</div>

<div class="my-5 border-t border-slate-200 pt-5"><h3 class="mb-4 text-sm font-black uppercase tracking-wider text-villa-800">Additional details</h3>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        @foreach([['timber_used','timber_unit','Timber Used'],['nails_used','nails_unit','Nail(s) Used']] as [$amount,$unit,$label])
        <div><span class="mb-1 block text-sm font-extrabold text-slate-700">{{ $label }} <b class="text-rose-600">*</b></span><div class="flex"><input type="number" min="0" step="0.01" name="{{ $amount }}" value="{{ old($amount, $current?->{$amount} ?? 0) }}" required class="min-h-11 min-w-0 flex-1 rounded-l-xl border border-r-0 border-slate-300 px-3"><select name="{{ $unit }}" required class="min-h-11 rounded-r-xl border border-slate-300 bg-blue-50 px-3 font-bold"><option value="PCS" @selected(old($unit,$current?->{$unit} ?? 'PCS')==='PCS')>PCS</option><option value="KG" @selected(old($unit,$current?->{$unit})==='KG')>KG</option></select></div></div>
        @endforeach
        <div><span class="mb-1 block text-sm font-extrabold text-slate-700">Fuel <b class="text-rose-600">*</b></span><div class="flex"><input type="number" min="0" step="0.01" name="fuel_consumed" value="{{ old('fuel_consumed', $current?->fuel_consumed ?? 0) }}" required class="min-h-11 min-w-0 flex-1 rounded-l-xl border border-r-0 border-slate-300 px-3"><input type="hidden" name="fuel_unit" value="LTRS"><span class="grid min-h-11 place-items-center rounded-r-xl border border-slate-300 bg-blue-50 px-4 font-bold text-slate-600">LTRS</span></div></div>
    </div>
</div>

<div class="grid gap-4 md:grid-cols-3">
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Total Soil Output (Bagon) <b class="text-rose-600">*</b></span><input type="number" min="0" name="soil_output" value="{{ old('soil_output', $current?->soil_output ?? 0) }}" required class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Total Coal Output (Bagon) <b class="text-rose-600">*</b></span><input type="number" min="0" name="coal_output" value="{{ old('coal_output', $current?->coal_output ?? 0) }}" required class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Excess / Deficit</span><input type="number" name="excess_deficit" value="{{ old('excess_deficit', $current?->excess_deficit) }}" placeholder="Use negative for deficit" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"><small class="mt-1 block text-xs text-slate-500">Positive = excess; negative = deficit.</small></label>
</div>
<label class="mt-4 block"><span class="mb-1 block text-sm font-extrabold text-slate-700">Remarks</span><textarea name="remarks" rows="3" maxlength="3000" class="w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('remarks', $current?->remarks) }}</textarea></label>
<label class="mt-4 block rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4"><span class="mb-1 block text-sm font-extrabold text-slate-700">Upload supporting documents</span><input type="file" name="attachments[]" multiple accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx" class="w-full text-sm"><small class="mt-2 block text-xs text-slate-500">Up to 5 files. PDF, image, Word, or Excel; maximum 10 MB each.</small></label>
