@php
    $input = 'h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm text-slate-800 outline-none transition focus:border-villa-500 focus:ring-4 focus:ring-villa-100';
    $editing = isset($report) && $report;
@endphp
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Date identified <b class="text-rose-600">*</b></span><input type="date" name="date_identified" max="{{ today()->toDateString() }}" value="{{ old('date_identified', $report?->date_identified?->toDateString() ?? today()->toDateString()) }}" class="{{ $input }}" required></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Vessel <b class="text-rose-600">*</b></span><select name="vessel_id" class="{{ $input }}" required><option value="">Select vessel</option>@foreach($vessels as $vessel)<option value="{{ $vessel->id }}" @selected((string) old('vessel_id', $report?->vessel_id) === (string) $vessel->id)>{{ $vessel->vessel_name }}</option>@endforeach</select></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Reported by <b class="text-rose-600">*</b></span><select name="reported_by_user_id" class="{{ $input }}" required><option value="">Select active Marine or Technical personnel</option>@foreach($reportingUsers as $person)<option value="{{ $person->id }}" @selected((string) old('reported_by_user_id', $report?->reported_by_user_id) === (string) $person->id)>{{ $person->name }} {{ $person->lastname }} — {{ $person->department?->name }}</option>@endforeach</select></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Port / Location</span><input type="text" name="port_location" maxlength="255" value="{{ old('port_location', $report?->port_location) }}" class="{{ $input }}" placeholder="Enter current port or location"></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">System affected <b class="text-rose-600">*</b></span><select name="system_affected" class="{{ $input }}" required><option value="">Select system</option>@foreach(\App\Http\Controllers\TechDefectController::SYSTEMS as $system)<option value="{{ $system }}" @selected(old('system_affected', $report?->system_affected) === $system)>{{ $system }}</option>@endforeach</select></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Severity <b class="text-rose-600">*</b></span><select name="severity_level" class="{{ $input }}" required><option value="">Select severity</option>@foreach(\App\Http\Controllers\TechDefectController::SEVERITIES as $severity)<option value="{{ $severity }}" @selected(old('severity_level', $report?->severity_level) === $severity)>{{ $severity }}</option>@endforeach</select></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Operational impact <b class="text-rose-600">*</b></span><select name="operational_impact" class="{{ $input }}" required><option value="">Select impact</option>@foreach(\App\Http\Controllers\TechDefectController::IMPACTS as $impact)<option value="{{ $impact }}" @selected(old('operational_impact', $report?->operational_impact) === $impact)>{{ $impact }}</option>@endforeach</select></label>
<label class="block"><span class="mb-2 block text-sm font-extrabold text-slate-700">Temporary repair done? <b class="text-rose-600">*</b></span><select name="temporary_repair" class="{{ $input }}" required><option value="">Select answer</option>@foreach(\App\Http\Controllers\TechDefectController::YES_NO as $answer)<option value="{{ $answer }}" @selected(old('temporary_repair', $report?->temporary_repair) === $answer)>{{ $answer }}</option>@endforeach</select></label>
<label class="block sm:col-span-2"><span class="mb-2 block text-sm font-extrabold text-slate-700">Defect description <b class="text-rose-600">*</b></span><textarea name="defect_description" rows="4" maxlength="5000" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-villa-500 focus:ring-4 focus:ring-villa-100" required>{{ old('defect_description', $report?->defect_description) }}</textarea></label>
<label class="block sm:col-span-2"><span class="mb-2 block text-sm font-extrabold text-slate-700">Initial cause</span><textarea name="initial_cause" rows="3" maxlength="5000" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-villa-500 focus:ring-4 focus:ring-villa-100">{{ old('initial_cause', $report?->initial_cause) }}</textarea></label>
<label class="block sm:col-span-2"><span class="mb-2 block text-sm font-extrabold text-slate-700">Remarks</span><textarea name="remarks" rows="3" maxlength="5000" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-villa-500 focus:ring-4 focus:ring-villa-100">{{ old('remarks', $report?->remarks) }}</textarea></label>
