@extends('layouts.app')
@section('title', 'Daily Production Monitoring | JMV Operations')
@section('content')
<section class="min-h-[calc(100svh-74px)] bg-slate-50 px-3 py-5 sm:px-6 lg:px-10"><div class="mx-auto max-w-[1600px]">
    @if(session('success'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><strong>Production log was not saved.</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <header class="mb-5 overflow-hidden rounded-3xl bg-gradient-to-r from-slate-950 via-villa-900 to-amber-600 p-5 text-white shadow-xl sm:p-7"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-black uppercase tracking-[.18em] text-amber-200">JMV Operations</p><h1 class="m-0 text-2xl font-black sm:text-3xl">Daily Production Monitoring</h1><p class="mt-1 text-sm text-white/75">Daily workforce, resource consumption, and mine production records.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('jmv.applications') }}" class="inline-flex min-h-11 items-center rounded-xl border border-white/20 bg-white/10 px-4 text-sm font-bold text-white no-underline">Back</a>@if($canManage)<button data-bs-toggle="modal" data-bs-target="#addProductionLog" class="inline-flex min-h-11 items-center gap-2 rounded-xl border-0 bg-amber-400 px-5 text-sm font-black text-slate-950"><i class="bi bi-plus-lg"></i>Add Log</button>@endif</div></div></header>

    <div class="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        @foreach([['Logs',$summary['logs'],'bi-journal-text','text-blue-700 bg-blue-50'],['Workers',$summary['workers'],'bi-people','text-violet-700 bg-violet-50'],['Soil Output',$summary['soil'].' Bagon','bi-layers','text-amber-700 bg-amber-50'],['Coal Output',$summary['coal'].' Bagon','bi-gem','text-slate-700 bg-slate-100'],['Fuel',number_format($summary['fuel'],2).' LTRS','bi-fuel-pump','text-emerald-700 bg-emerald-50']] as [$label,$value,$icon,$tone])
        <article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span class="mb-3 grid h-10 w-10 place-items-center rounded-xl {{ $tone }}"><i class="bi {{ $icon }}"></i></span><p class="mb-1 text-xs font-extrabold uppercase tracking-wider text-slate-500">{{ $label }}</p><p class="m-0 text-2xl font-black text-slate-900">{{ $value }}</p></article>
        @endforeach
    </div>

    <form method="GET" class="mb-4 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_170px_190px_190px_auto_auto]">
        <label><span class="mb-1 block text-xs font-extrabold uppercase text-slate-500">Search</span><input name="search" value="{{ request('search') }}" placeholder="Location, shift, leadman or foreman" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
        <label><span class="mb-1 block text-xs font-extrabold uppercase text-slate-500">Month</span><input type="month" name="month" value="{{ request('month') }}" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
        <label><span class="mb-1 block text-xs font-extrabold uppercase text-slate-500">Location</span><select name="location" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">All locations</option>@foreach($locations as $location)<option @selected(request('location')===$location)>{{ $location }}</option>@endforeach</select></label>
        <label><span class="mb-1 block text-xs font-extrabold uppercase text-slate-500">Shift</span><select name="shift" class="min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">All shifts</option>@foreach($shifts as $shift)<option @selected(request('shift')===$shift)>{{ $shift }}</option>@endforeach</select></label>
        <button class="mt-auto min-h-11 rounded-xl border-0 bg-villa-800 px-5 text-sm font-bold text-white">Apply</button><a href="{{ route('jmv.operations.production.index') }}" class="mt-auto grid min-h-11 place-items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700 no-underline">Reset</a>
    </form>
    @if($canExport)<div class="mb-4 flex justify-end"><a href="{{ route('jmv.operations.production.export', request()->query()) }}" class="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-700 px-5 text-sm font-extrabold text-white no-underline"><i class="bi bi-file-earmark-spreadsheet"></i>Export to Excel</a></div>@endif

    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[1420px] text-left text-sm"><thead class="bg-villa-900 text-xs uppercase tracking-wider text-white"><tr>@foreach(['Date / Log No.','Location','Shift','Leadman','Foreman','Workers','Timber','Nails','Fuel','Soil Output','Coal Output','Excess / Deficit','Action'] as $head)<th class="whitespace-nowrap px-4 py-4">{{ $head }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($logs as $log)<tr class="hover:bg-amber-50/40"><td class="px-4 py-4"><strong class="block">{{ $log->log_date->format('M d, Y') }}</strong><span class="text-xs text-slate-500">{{ $log->log_no }}</span></td><td class="px-4 py-4 font-bold">{{ $log->location }}</td><td class="px-4 py-4">{{ $log->shift }}</td><td class="px-4 py-4">{{ $log->leadman }}</td><td class="px-4 py-4">{{ $log->foreman }}</td><td class="px-4 py-4 font-black">{{ number_format($log->total_workers) }}</td><td class="px-4 py-4">{{ number_format($log->timber_used,2) }} {{ $log->timber_unit }}</td><td class="px-4 py-4">{{ number_format($log->nails_used,2) }} {{ $log->nails_unit }}</td><td class="px-4 py-4">{{ number_format($log->fuel_consumed,2) }} LTRS</td><td class="px-4 py-4 font-bold text-amber-700">{{ number_format($log->soil_output) }}</td><td class="px-4 py-4 font-bold text-slate-800">{{ number_format($log->coal_output) }}</td><td class="px-4 py-4 font-black {{ ($log->excess_deficit ?? 0)<0?'text-rose-700':'text-emerald-700' }}">{{ is_null($log->excess_deficit)?'—':(($log->excess_deficit>0?'+':'').number_format($log->excess_deficit)) }}</td><td class="px-4 py-4"><a href="{{ route('jmv.operations.production.show',$log) }}" class="rounded-lg border border-villa-200 bg-villa-50 px-3 py-2 text-xs font-bold text-villa-800 no-underline">View</a></td></tr>
        @empty<tr><td colspan="13" class="px-6 py-16 text-center text-slate-500"><i class="bi bi-journal-x mb-2 block text-3xl text-slate-300"></i>No daily production logs found.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-slate-100 p-4">{{ $logs->links() }}</div></div>
</div></section>

<datalist id="productionLocations">@foreach($locations as $location)<option value="{{ $location }}">@endforeach<option value="Mine 1"><option value="Mine 2"></datalist>
<datalist id="productionShifts">@foreach($shifts as $shift)<option value="{{ $shift }}">@endforeach<option value="8:00 AM - 5:00 PM"><option value="5:00 PM - 2:00 AM"></datalist>

@if($canManage)<div class="modal fade" id="addProductionLog" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><form method="POST" enctype="multipart/form-data" action="{{ route('jmv.operations.production.store') }}" class="modal-content overflow-hidden rounded-4 border-0 shadow-2xl">@csrf<div class="modal-header border-bottom px-4 py-3"><div><p class="mb-1 text-xs font-black uppercase tracking-wider text-amber-700">JMV Operations</p><h2 class="modal-title fs-4 fw-black">New Daily Production Log</h2></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body bg-slate-50 px-4 py-4 sm:px-5">@include('jmv.operations.production.partials.form')</div><div class="modal-footer border-top bg-white"><button type="button" class="btn btn-light rounded-3" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary rounded-3 px-4"><i class="bi bi-check-circle me-2"></i>Save Log</button></div></form></div></div></div>@endif
@endsection
@push('scripts')
@if($errors->any() && $canManage)<script>document.addEventListener('DOMContentLoaded',()=>bootstrap.Modal.getOrCreateInstance(document.getElementById('addProductionLog')).show());</script>@endif
@endpush
