@extends('layouts.app')
@section('title', $log->log_no.' | JMV Daily Production')
@section('content')
<section class="min-h-[calc(100svh-74px)] bg-slate-50 px-4 py-6 sm:px-7 lg:px-10"><div class="mx-auto max-w-6xl">
    @if(session('success'))<div class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
    <a href="{{ route('jmv.operations.production.index') }}" class="mb-4 inline-flex items-center gap-2 text-sm font-bold text-villa-700 no-underline"><i class="bi bi-arrow-left"></i>Back to daily monitoring</a>
    <header class="mb-5 rounded-3xl bg-gradient-to-r from-slate-950 via-villa-900 to-amber-600 p-6 text-white shadow-xl"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-black uppercase tracking-[.18em] text-amber-200">Daily Production Log</p><h1 class="m-0 text-2xl font-black sm:text-3xl">{{ $log->log_no }}</h1><p class="mt-1 text-sm text-white/75">{{ $log->log_date->format('F d, Y') }} · {{ $log->location }} · {{ $log->shift }}</p></div>@if($canManage)<a href="{{ route('jmv.operations.production.edit',$log) }}" class="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-5 text-sm font-black text-villa-900 no-underline"><i class="bi bi-pencil-square"></i>Edit Log</a>@else<span class="w-fit rounded-full border border-white/20 bg-white/10 px-3 py-2 text-xs font-bold"><i class="bi bi-eye me-1"></i>Read-only</span>@endif</div></header>

    <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
        <div class="space-y-5">
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-black text-slate-900">Operation details</h2><dl class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@foreach([['Date',$log->log_date->format('F d, Y')],['Location',$log->location],['Shift',$log->shift],['Leadman',$log->leadman],['Foreman',$log->foreman],['Total Workers',number_format($log->total_workers)]] as [$label,$value])<div><dt class="text-xs font-extrabold uppercase tracking-wider text-slate-400">{{ $label }}</dt><dd class="mt-1 font-bold text-slate-900">{{ $value }}</dd></div>@endforeach</dl></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-black text-slate-900">Resource utilization</h2><div class="grid gap-3 sm:grid-cols-3">@foreach([['Timber Used',number_format($log->timber_used,2).' '.$log->timber_unit,'bg-amber-50 text-amber-800'],['Nails Used',number_format($log->nails_used,2).' '.$log->nails_unit,'bg-blue-50 text-blue-800'],['Fuel Consumed',number_format($log->fuel_consumed,2).' LTRS','bg-emerald-50 text-emerald-800']] as [$label,$value,$tone])<div class="rounded-xl p-4 {{ $tone }}"><span class="block text-xs font-black uppercase">{{ $label }}</span><strong class="mt-2 block text-xl">{{ $value }}</strong></div>@endforeach</div></article>
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-lg font-black text-slate-900">Production output</h2><div class="grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-amber-50 p-4 text-amber-900"><span class="text-xs font-black uppercase">Soil Output</span><strong class="mt-2 block text-2xl">{{ number_format($log->soil_output) }} <small class="text-sm">Bagon</small></strong></div><div class="rounded-xl bg-slate-100 p-4 text-slate-900"><span class="text-xs font-black uppercase">Coal Output</span><strong class="mt-2 block text-2xl">{{ number_format($log->coal_output) }} <small class="text-sm">Bagon</small></strong></div><div class="rounded-xl p-4 {{ ($log->excess_deficit??0)<0?'bg-rose-50 text-rose-900':'bg-emerald-50 text-emerald-900' }}"><span class="text-xs font-black uppercase">Excess / Deficit</span><strong class="mt-2 block text-2xl">{{ is_null($log->excess_deficit)?'Not recorded':(($log->excess_deficit>0?'+':'').number_format($log->excess_deficit)) }}</strong></div></div>@if($log->remarks)<div class="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700"><b class="mb-1 block">Remarks</b>{{ $log->remarks }}</div>@endif</article>
        </div>
        <aside class="space-y-5">
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-base font-black text-slate-900">Supporting documents ({{ $log->attachments->count() }})</h2>@forelse($log->attachments as $attachment)<a href="{{ route('jmv.operations.production.attachments.show',[$log,$attachment]) }}" class="mb-2 flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm text-slate-700 no-underline hover:bg-slate-50"><i class="bi bi-paperclip text-lg text-blue-700"></i><span class="min-w-0"><b class="block truncate">{{ $attachment->original_name }}</b><small class="text-slate-400">{{ number_format($attachment->size_bytes/1024,1) }} KB · {{ $attachment->created_at->format('M d, Y h:i A') }}</small></span></a>@empty<p class="text-sm text-slate-500">No document uploaded.</p>@endforelse</article>
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-base font-black text-slate-900">Record history</h2><div class="space-y-4">@forelse($log->audits as $audit)<div class="border-l-2 border-amber-400 pl-3"><b class="block text-sm capitalize text-slate-800">{{ str_replace('_',' ',$audit->action) }}</b><small class="text-slate-500">{{ trim(($audit->user?->name??'').' '.($audit->user?->lastname??'')) ?: 'System' }}<br>{{ $audit->created_at?->format('M d, Y h:i A') }}</small></div>@empty<p class="text-sm text-slate-500">No audit activity.</p>@endforelse</div><div class="mt-5 border-t border-slate-100 pt-4 text-xs text-slate-500">Created by {{ trim(($log->creator?->name??'').' '.($log->creator?->lastname??'')) ?: 'System' }} on {{ $log->created_at->format('M d, Y h:i A') }}</div></article>
        </aside>
    </div>
</div></section>
@endsection
