@extends('layouts.app')
@section('title','Notifications | Villa Group')
@section('content')
<section class="min-h-[calc(100svh-74px)] bg-slate-50 px-4 py-7 sm:px-8"><div class="mx-auto max-w-4xl">
<header class="mb-6 flex items-center justify-between gap-4"><div><p class="mb-1 text-xs font-extrabold uppercase tracking-[.16em] text-villa-600">Activity centre</p><h1 class="m-0 text-3xl font-black text-slate-900">Notifications</h1></div><form method="POST" action="{{ route('notifications.read-all') }}">@csrf<button class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700 shadow-sm">Mark all read</button></form></header>
@if(session('success'))<div class="mb-4 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">@forelse($notifications as $notification)<form method="POST" action="{{ route('notifications.read',$notification->id) }}" class="border-b border-slate-100 last:border-0">@csrf<button class="flex w-full gap-4 p-5 text-left hover:bg-slate-50"><span class="mt-1 grid h-10 w-10 shrink-0 place-items-center rounded-xl {{ $notification->read_at?'bg-slate-100 text-slate-500':'bg-villa-100 text-villa-700' }}"><i class="bi bi-wrench-adjustable-circle"></i></span><span class="min-w-0 flex-1"><span class="block font-black text-slate-900">{{ $notification->data['title'] ?? 'Technical defect update' }}</span><span class="mt-1 block text-sm leading-6 text-slate-600">{{ $notification->data['message'] ?? '' }}</span><span class="mt-2 block text-xs font-bold text-slate-400">{{ $notification->created_at->diffForHumans() }}</span></span>@unless($notification->read_at)<span class="mt-3 h-2.5 w-2.5 rounded-full bg-blue-500"></span>@endunless</button></form>@empty<div class="p-12 text-center text-slate-500"><i class="bi bi-bell-slash mb-3 block text-3xl"></i>No notifications yet.</div>@endforelse</div><div class="mt-5">{{ $notifications->links() }}</div>
</div></section>
@endsection
